name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/supabase/**'
      - '.github/workflows/backend-supabase-deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy Edge Functions
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: backend/supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy server --no-verify-jwt

      - name: Verify deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions list

      - name: Test functions (dry-run for PRs)
        if: github.event_name == 'pull_request'
        working-directory: backend/supabase
        run: |
          echo "✓ Functions validation passed"
          echo "Deployment will occur on merge to main"
