blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/magdee
    about: Join our Discord server for questions and community support
  - name: 📚 Documentation
    url: https://github.com/yourusername/magdee/wiki
    about: Check our documentation for guides and API references
  - name: 🔒 Security Vulnerability
    url: https://github.com/yourusername/magdee/security/advisories/new
    about: Report security vulnerabilities privately
