export const BOOKS_DATA = [
  {
    id: "1",
    title: "Handling Problems",
    author: "Nile Williams",
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
    duration: "4h 30m",
    chapters: 12,
    genre: "Self-Help",
    rating: 4.5,
    progress: 45,
    description: "A practical guide to solving life's challenges with proven strategies and mindful approaches to problem-solving.",
    dateAdded: "2 days ago",
    category: "Self-Help"
  },
  {
    id: "2",
    title: "Laws of Success",
    author: "Napoleon Hill",
    cover: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=300&h=400&fit=crop",
    duration: "12h 15m",
    chapters: 16,
    genre: "Business",
    rating: 4.7,
    progress: 72,
    description: "The definitive guide to achieving success through time-tested principles and the psychology of achievement.",
    dateAdded: "1 week ago",
    category: "Business"
  },
  {
    id: "3",
    title: "The Art of War",
    author: "Sun Tzu",
    cover: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=300&h=400&fit=crop",
    duration: "2h 15m",
    chapters: 13,
    genre: "Philosophy",
    rating: 4.4,
    progress: 25,
    description: "Ancient Chinese military treatise offering timeless strategies for conflict and leadership.",
    dateAdded: "2 weeks ago",
    category: "Philosophy"
  },
  {
    id: "4",
    title: "Atomic Habits",
    author: "James Clear",
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
    duration: "5h 30m",
    chapters: 20,
    genre: "Self-Help",
    rating: 4.8,
    progress: 78,
    description: "An easy and proven way to build good habits and break bad ones with practical strategies.",
    dateAdded: "3 weeks ago",
    category: "Self-Help"
  },
  {
    id: "5",
    title: "Deep Work",
    author: "Cal Newport",
    cover: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&h=400&fit=crop",
    duration: "7h 44m",
    chapters: 15,
    genre: "Productivity",
    rating: 4.6,
    progress: 23,
    description: "Rules for focused success in a distracted world, teaching you to master hard things quickly.",
    dateAdded: "1 month ago",
    category: "Productivity"
  },
  {
    id: "6",
    title: "The Lean Startup",
    author: "Eric Ries",
    cover: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop",
    duration: "8h 32m",
    chapters: 12,
    genre: "Entrepreneurship",
    rating: 4.3,
    progress: 100,
    description: "A scientific approach to creating and managing successful startups in an age of uncertainty.",
    dateAdded: "2 months ago",
    category: "Business"
  }
];