name: Magdee CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: ./src
        
      - name: Install Vite globally
        run: npm install -g vite
        working-directory: ./src
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json 
          npm install --legacy-peer-deps

      - name: Build project
        run: npm run build 

  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run backend tests
        run: pytest || echo "No tests yet"
